package store

import "time"

// Tenant is one isolated WireGuard environment: its own network namespace,
// its own subnet, its own server keypair and peer defaults.
type Tenant struct {
	ID               int64
	Name             string
	Subnet           string // CIDR, e.g. "10.8.0.0/24"
	ListenPort       int
	ServerPrivateKey string // decrypted on read
	ServerPublicKey  string
	DNS              string
	AllowedIPs       string // default AllowedIPs handed to new peers
	Keepalive        int    // default PersistentKeepalive, seconds
	PSKRequired      bool   // generate a preshared key for new peers by default
	IsolatePeers     bool   // firewall peers off from each other within the tenant
	CreatedAt        time.Time
}

// TenantInput is the set of fields an operator provides when creating a
// tenant; ServerPrivateKey/ServerPublicKey are generated by the caller
// (cmd layer) via wgconf before calling Store.CreateTenant.
type TenantInput struct {
	Name             string
	Subnet           string
	ListenPort       int
	ServerPrivateKey string
	ServerPublicKey  string
	DNS              string
	AllowedIPs       string
	Keepalive        int
	PSKRequired      bool
	IsolatePeers     bool
}

// Peer is one road-warrior config within a tenant.
type Peer struct {
	ID           int64
	TenantID     int64
	Name         string
	Address      string // single host IP, e.g. "10.8.0.2"
	PublicKey    string
	PrivateKey   string // decrypted on read
	PresharedKey string // decrypted on read; empty if not used
	AllowedIPs   string
	DNS          string
	Keepalive    int
	CreatedAt    time.Time
}

// PeerInput is the set of fields needed to create a peer.
type PeerInput struct {
	TenantID     int64
	Name         string
	Address      string
	PublicKey    string
	PrivateKey   string
	PresharedKey string
	AllowedIPs   string
	DNS          string
	Keepalive    int
}
